apiVersion: v1
kind: Secret
metadata:
  name: localstack-creds
  namespace: crossplane-system
type: Opaque
stringData:
  credentials: |
    [default]
    aws_access_key_id = test
    aws_secret_access_key = test
---
apiVersion: aws.upbound.io/v1beta1
kind: ProviderConfig
metadata:
  name: default
spec:
  credentials:
    source: Secret
    secretRef:
      namespace: crossplane-system
      name: localstack-creds
      key: credentials
  endpoint:
    url:
      type: Static
      static: http://localstack.localstack.svc.cluster.local:4566
    services: ["s3", "sts", "sqs", "iam"]
  s3_use_path_style: true
  skip_requesting_account_id: true